### ISSUE TITLE
Feature Request: Field to enter "Note" in Bulk Creation of Samples/Libraries

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#1243]
We store docs like BA images on an external server and only put links to these documents in sample/library notes.

In older versions of MISO it was possible to create "notes" during bulk sample/library creation. Would be great to have this back.

How do you store documents from BioAnalyzer or other devices? Or, better, how do you connect samples/libraries in MISO with "external" items like gel/BA images or something similar?

**Comment by callunity** [comment]
We don't currently connect samples/libraries in MISO with external items. I'll add this feature request to our backlog.

**Comment by djcooke** [comment]
Because a sample (and other entities) can have multiple notes, it is confusing to include a "Note" field on the bulk create and edit sample pages. Another option is to add separate bulk "Add Notes" and "Edit Notes" pages, similar to the existing Add/Edit QCs pages. Would this be an acceptable solution?

**Comment by sklages** [comment]
I discussed that with the lab and we agreed that this would be even the better solution. So, "Yes" :-)
