### ISSUE TITLE
biosample metadata add-on?

### ISSUE THREAD

**Issue by rec3141** [miso-lims/miso-lims#1456]
MISO looks very useful for the management of my lab's sequencing workflow, but additional functionality that allowed it to serve as a biosample database would really make it more useful for scientists rather than just lab managers. Specifically if it could import/export Biosample metadata sheets from the SRA and include that info in the SRA submission process that would be amazing. Is there any thought towards doing this at some stage? How hard would it be to implement if I wanted to try it myself or hire someone to do it? thanks

https://submit.ncbi.nlm.nih.gov/biosample/template/

**Comment by apmasell** [comment]
Hi. We're not really using the SRA submission in MISO, so there's probably a lot of updates needed. I also think it was mean to target the ERA rather than SRA, so it might need work anyway.

It shouldn't be difficult to add biosample information to MISO. We've expanded MISO a while back to include more information about samples. We have the concept of a “identity” (donor/patient/individual organism), that gets separated down to tissues, tissue processing (e.g., dissection), to stocks of extracted DNA (roughly equivalent to MISO's samples). It seems like these categories could be added to those different levels (at least for humans/vertebrates/plants). I'm not sure how clean the connection would be for viruses and microbiomes (and beta-lactamase...that's very specific). There's already some tissue type stuff that would be pretty similar. You can turn this functionality on by setting `miso.detailed.sample.enabled:true` in `miso.properties`. Then, create your different things in the `SampleClass` table and connect them via the `SampleValidRelationship`.

Here's the tables from our production database for reference:
```
INSERT INTO `SampleClass` VALUES (1,'Identity','Identity',NULL,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(8,'Curls','Tissue Processing','C',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(10,'LCM Tube','Tissue Processing','LCM',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(11,'gDNA (stock)','Stock','D_S',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(12,'gDNA_wga (stock)','Stock','D_S',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(13,'whole RNA (stock)','Stock','R_S',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',1),(14,'cDNA (stock)','Stock','D_S',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(15,'gDNA (aliquot)','Aliquot','D_',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(16,'gDNA_wga (aliquot)','Aliquot','D_',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(17,'whole RNA (aliquot)','Aliquot','R_',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(18,'smRNA','Aliquot','SM_',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(19,'mRNA','Aliquot','MR_',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(20,'rRNA_depleted','Aliquot','WT_',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(21,'cDNA (aliquot)','Aliquot','D_',1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(23,'Tissue','Tissue',NULL,1,'2017-05-29 20:01:44',1,'2017-05-29 20:01:44',0),(24,'Slide','Tissue Processing','SL',1,'2017-06-09 17:59:19',1,'2017-06-09 17:59:19',0);

INSERT INTO `SampleValidRelationship` VALUES (23,8,11,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(24,10,11,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(25,10,13,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(26,11,11,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(27,11,12,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(28,11,15,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(29,12,12,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(30,12,16,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(31,13,13,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(32,13,14,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(33,13,17,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(34,14,14,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(35,14,21,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(36,17,18,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(37,17,19,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(38,17,20,1,'2016-09-26 15:55:44',1,'2016-09-26 15:55:44',0),(59,13,20,1,'2016-09-26 15:55:46',1,'2016-09-26 15:55:46',1),(60,13,18,1,'2016-09-27 20:44:05',1,'2016-09-27 20:44:05',1),(61,13,19,1,'2016-09-27 20:44:05',1,'2016-09-27 20:44:05',1),(62,11,16,1,'2016-10-11 20:12:54',1,'2016-10-11 20:12:54',1),(63,13,21,1,'2016-10-11 20:12:54',1,'2016-10-11 20:12:54',1),(64,15,16,1,'2016-10-25 20:50:33',1,'2016-10-25 20:50:33',1),(67,15,15,1,'2016-11-15 21:14:46',1,'2016-11-15 21:14:46',1),(69,8,13,1,'2016-12-13 23:05:28',1,'2016-12-13 23:05:28',0),(77,1,23,1,'2017-05-29 20:01:47',1,'2017-05-29 20:01:47',0),(84,23,8,1,'2017-05-29 20:01:47',1,'2017-05-29 20:01:47',0),(86,23,10,1,'2017-05-29 20:01:47',1,'2017-05-29 20:01:47',1),(87,23,11,1,'2017-05-29 20:01:47',1,'2017-05-29 20:01:47',0),(88,23,12,1,'2017-05-29 20:01:47',1,'2017-05-29 20:01:47',0),(89,23,13,1,'2017-05-29 20:01:47',1,'2017-05-29 20:01:47',0),(90,23,14,1,'2017-05-29 20:01:47',1,'2017-05-29 20:01:47',0),(92,23,23,1,'2017-05-29 20:01:47',1,'2017-05-29 20:01:47',0),(93,24,10,1,'2016-09-26 15:55:44',1,'2017-06-09 17:59:19',0),(94,24,11,1,'2016-12-20 18:36:34',1,'2017-06-09 17:59:19',0),(95,24,13,1,'2016-12-20 18:36:34',1,'2017-06-09 17:59:19',0),(96,23,24,1,'2017-05-29 20:01:47',1,'2017-06-09 17:59:19',0);
```
Here's our tutorial for dealing with these kinds of samples: http://oicr-gsi.github.io/miso-docs-oicr/2-0-samples

If it's something you wanted to do yourself/hire someone to do, we'd be happy to give them guidance about how to make the modifications. Most of the work on their part would be deciding what subset of the SRA data is necessary and where in MISO to capture it and then updating the SRA generator to use it.
