### ISSUE TITLE
SampleAliasGenerator & Detailed Sample Mode

### ISSUE THREAD

**Issue by bmatlas** [miso-lims/miso-lims#1764]
When Project -> Create Samples appears an error message:

> The following rows failed to save:
    Row 1: check hasSampleAliasGenerator() to determine availability

I am wondering if I have forgotten something in miso.properties?

```
miso.detailed.sample.enabled:true
miso.naming.scheme:default
miso.naming.validator.sample.alias:default
miso.naming.validator.sample.alias.regex:([0-9]+|[0-9]+R[0-9]+)_([0-9a-zA-Z-]+)
```

**Comment by djcooke** [comment]
What class/category of sample are you trying to create?

I'm guessing you're creating a Tissue, or something lower in the hierarchy. Since you're _creating_ or _receiving_ the sample, rather than _propagating_ from an existing sample, it has to construct the upper sample hierarchy at the same time. This means that it has to generate aliases for the Identity and/or any ghost samples that are created. You probably entered an alias for the sample you're creating, but this requirement to generate aliases for ghost samples caused the save to fail.

This is a bug in MISO. Detailed sample mode needs to either require a sample alias generator, or allow the user to enter all of the parent sample aliases when creating/receiving a sample (which could easily get annoying).

Two possible work-arounds for now:

* Configure a sample alias generator. Or
* Create all of the samples explicitly so that no ghost samples are ever generated. This means creating first an Identity sample, propagating from the Identity to a create a Tissue, propagating from the Tissue to create a Tissue Processing or Stock, etc.

**Comment by bmatlas** [comment]
Yes, you are right. I tried to create a ‘Tissue’ class. When created ‘Identity’ and propagated ‘Tissue’ -> .... it works. As a work-around, using the sample alias generator would be a good idea. Many Thank’s.

**Comment by djcooke** [comment]
Reopening as this is a bug that we'll need to fix. Most likely this will involve making it so that non-Identity samples can only be created/received if there is a sample alias generator configured. Otherwise, Identities will need to be created manually, and all other samples propagated from there.

**Comment by bmatlas** [comment]
Until a DefaultSampleAliasGenerator is released, we tried to use the OicrSampleAliasGenerator instead. However, this generator uses the Project Short Name. Since the short name with varchar(5) is too short for us, we have tried to leave Project Short Name free in the hope it will replaced by the Project Alias.  But that doesn't work, project fields are marked red and neither can be selected nor entered.
Do you have any idea for a work-around here?

**Comment by djcooke** [comment]
There are assumptions in the code that project short name will always be used in detailed sample mode - at least with the `OicrSampleAliasGenerator`. We should probably add a `DefaultSampleAliasGenerator` that will generate aliases matching the default pattern in `DefaultSampleAliasValidator`.

In the meantime, I think the only work-around is to manually create each level of the sample hierarchy independently - create the Identity, propagate to Tissue, propagate to Stock, etc.

**Comment by djcooke** [comment]
Oh - I misunderstood the other issue for a moment. Project short name is used to label the Project column values in detailed sample mode, which means that if you don't have short names, you can't select a project. The only work-around for this would be to set short names. We'll fix it to display the project alias if short names aren't present

**Comment by sklages** [comment]
In `v0.2.160` the project short name has been lengthened, to `varchar(255)`.

**Comment by djcooke** [comment]
#2440 changes short name to be required in detailed sample mode, as several things depend on it
