### ISSUE TITLE
Propagate to Library and "Non -standard alias on parent Sample"

### ISSUE THREAD

**Issue by LenaCostecalde** [miso-lims/miso-lims#2029]
Hello !

We have deployed MISO LIMS in our Lab, and I am trying to save all the ancient Samples / Libraries / Pools / Runs we had before, on the software.
It has worked amazing until today, when I was trying to Propagate Libraries from gDNA.

The following error occured on each and every row "Row 1: Cannot generate alias due to non-standard alias on parent Sample".

I don't understand it because the Aliases were only generated automatically by MISO, since the beginning of our use !

If you have a clue on that, please feel free to share.
Thanks !

**Comment by LenaCostecalde** [comment]
![image](https://user-images.githubusercontent.com/54105038/63019808-53178b80-be94-11e9-837a-4ead4018b49d.png)
![image](https://user-images.githubusercontent.com/54105038/63019842-688cb580-be94-11e9-8c68-e50d938f36d1.png)
Here are the errors and the Sample Aliases concerned.

**Comment by avarsava** [comment]
Hi Lena,

My first suspicion is that there is an issue with the naming settings in your configuration.

Could you please tell me the following values from your $CATALINA_HOME/conf/Catalina/localhost/miso.properties file?
- miso.detailed.sample.enabled
- miso.naming.scheme
- any other values in miso.properties which begin with 'miso.naming'

Could you also please tell me if anyone has changed those settings since you started adding samples to MISO?

These details will help us better identify the cause of the problem.

Regards,
Alexis

**Comment by LenaCostecalde** [comment]
Hi, 

Here are the values I found in the naming settings : 



    * miso.detailed.sample.enabled true 
    * miso.naming.scheme oicr 
    * any other values in miso.properties which begin with 'miso.naming' no other values 

And nobody has changed anything in those settings since the beginning of our use. 

Regards, 

Léna COSTECALDE 
Elève en 2ème année 
Option BioSTIC-Santé 
lena.costecalde@eleves.ec-nantes.fr 
06 85 27 34 62 


De: "Alexis Varsava" <notifications@github.com> 
À: "miso-lims/miso-lims" <miso-lims@noreply.github.com> 
Cc: "Lena Costecalde" <lena.costecalde@eleves.ec-nantes.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 14 Août 2019 20:07:20 
Objet: Re: [miso-lims/miso-lims] Propagate to Library and "Non -standard alias on parent Sample" (#2029) 



Hi Lena, 

My first suspicion is that there is an issue with the naming settings in your configuration. 

Could you please tell me the following values from your $CATALINA_HOME/conf/Catalina/localhost/miso.properties file? 

    * miso.detailed.sample.enabled true 
    * miso.naming.scheme oicr 
    * any other values in miso.properties which begin with 'miso.naming' no other values 


Could you also please tell me if anyone has changed those settings since you started adding samples to MISO? 

These details will help us better identify the cause of the problem. 

Regards, 
Alexis

**Comment by avarsava** [comment]
HI Lena,
We have identified the cause of the issue! It looks like our name validation code works with the assumption that Tissue Type aliases will only ever be 1 letter long, so your Tissue Type alias (Mg) is causing the library name validation to fail.
This is a bug and we will fix it; you don't need to change your Tissue Type aliases. I'll let you know when to expect a patch.
Thanks,
Alexis

**Comment by LenaCostecalde** [comment]
Hi,

Thanks for your quick answer !
I quit my internship at the end of the week, do you think I will be able to finish my Libraries propagations before I quit ? Will the bug be fixed then ?
Otherwise I will have to train someone else quickly to finish it later...

Thanks a lot,
Regards,
Léna

**Comment by avarsava** [comment]
Hi Léna,

We're working on a fix for the bug right now; it should be available in our next release of MISO, which won't be out until September 3rd. The work in progress can be viewed here: https://github.com/miso-lims/miso-lims/pull/2039 You can try checking out this branch and deploying it and seeing if it helps you with your issue, but it is a work in progress. Otherwise you can wait for the next release.

If you'd like to work around the bug, you can also change your Tissue Type aliases to be a single letter long then update your Sample aliases to reflect the new names. Library names should then be able to be automatically generated.

Regards,
Alexis

**Comment by LenaCostecalde** [comment]
Hi,

Thanks a lot for your answers ! I have changed my Tissue Type aliases in order to work until the next release.
Amazing jobs, thanks again for your reactivity.

Regards,
Léna
