### ISSUE TITLE
Q: Pinery MISO Usage | Starting points

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2067]
We need to implement some kind of "where-is-my-sequencing-library-currently?" webinterface for our colleagues in the institute to check their sample queue.

So we would need to read some sample/library-related things from the database, e.g. if the QC has passed or not, if there is already a library created  and if it passed QC or not etc.

For this I'd use Pinery MISO, write some flat files once or twice a day and finally evaluate these flat files to provide the requested infos.

I deployed and configured MISO accordingly. 

Using
```
curl -X GET --header "Accept: application/json" "http://miso_server/pinery-miso/sample-provenance"
```
I get a JSON string with a lot of (but not all?) infos on samples.

What I desperately miss (because I probably didn't find it) is some (MISO-related) documentation and some usage examples.

- `sample-provenance` - are there additional things to ask for?

I found `Pinery-to-Flatfile Exporter` .. I am not sure if this is still in usage?
```
java -jar ./tomcat/webapps/pinery-miso/WEB-INF/lib/pinery-lims-flatfile-2.5.0.jar http://miso_server/pinery-miso out_dir abc
no main manifest attribute, in ./tomcat/webapps/pinery-miso/WEB-INF/lib/pinery-lims-flatfile-2.5.0.jar
```
So again I probably misunderstood the docs .. :-(

Any starting points, examples, pointers to docs on how to use pinery-miso for data extraction are welcome.

Or any other strategy to provide some basic status data without accessing MISO directly..

**Comment by djcooke** [comment]
You might want to have a look at the `/samples` endpoint rather than `/sample-provenance`. Sample provenance is a specialized and filtered collection that we use for analysis, whereas the regular sample model contains more data and all the samples. Some attributes may still not be included, while others may have different names since Pinery is an abstraction layer and not all of the terms are MISO-specific. Let us know if you have trouble finding anything. If you navigate to the webapp root (http://miso_server/pinery-miso/) in your browser, there's a link to the API docs that may help too.

The main Pinery repository is here: https://github.com/oicr-gsi/pinery and documentation for the flatfile writer is linked in the main readme. You can clone the Pinery repo, checkout the tag for the same version used by the version of MISO you're using (Pinery 2.5.0 for latest MISO release currently; otherwise check the pom.xml file for pinery-miso to find the pinery version), and then build and run the flatfile writer from there.

**Comment by sklages** [comment]
`/samples` is very clear but somewhat incomplete. 

What I'd like to achieve is to compile a dataset for further (external) analysis of all samples of a given project, containing the infos on its way through the lab to the sequencer.

So ideally one record per sample, with dates, qc pass/fail, concentrations for the sample itself and, if already available, for one library, with dates, qc pass/fail, concentrations, its barcodes etc. If the sample (its library aliquot) finally has run on sequencer, which run. 
If there is a second library, create new record for the sample.

This would be used to implement some kind of web-based "status monitor" when a colleague is requesting info on where his samples actually are in the sequencing process.

I am not sure if I can compile that data with pinery-miso .. how would you try to achieve that with pinery? How do you provide your users with info about the current status of a sample?

Alternatively I could use the "hard way" querying the database directly.
This seems quite complicated to me: 
first I would need to follow the path from the seqencing runs back (or up) to the projects, to get all relevant info on libraries and samples which made it to sequencer and are "fully processed". 
In another query I would need to fetch all the infos from **all** libraries  and subtract it from the first results set to get all libraries, which are actively being worked on but which have not been loaded on a sequencer yet.
In a third query I'd go through all samples to get info on which samples are being worked on, but there has not been a library created yet.

Do you get what I mean? This seems quite complicated to me, There must be an easier way to describe the pathway of samples of a given project, from sample submission to sequencer run.

I will not be writing the web-based "status monitor", I just need to provide the "raw data" in kinda complete and parsable data format.

I am stuck in searching for the right strategy .. any ideas are welcome :-)

**Comment by djcooke** [comment]
I think Pinery has all of the information you need, and it can be used similarly to how you'd query the database

> follow the path from the seqencing runs back (or up) to the projects, to get all relevant info on libraries and samples which made it to sequencer and are "fully processed"

Get all runs from Pinery, which will get you the sample IDs of the library aliquots on each run. Note that samples, libraries, and library aliquots are all considered "samples" in Pinery. You can then go through the samples collection to find parent libraries and samples.

> fetch all the infos from all libraries and subtract it from the first results set to get all libraries, which are actively being worked on but which have not been loaded on a sequencer yet

Get all samples from Pinery, filter to include only libraries, filter again to remove any of the libraries included in the previous step

> get info on which samples are being worked on, but there has not been a library created yet.

Get all samples from Pinery and filter to include only those with no children.

Is there anything missing from that?

We use Pinery rather than have other applications query the MISO database directly for a few reasons

* Pinery data can be cached using flat files, so the MISO database doesn't have to be hit very often and MISO performance isn't affected
* Data is abstracted and not in MISO-specific format. This helped us to migrate from our old LIMS to MISO and also allows us to more easily integrate different data sources with the MISO data
* Pinery models are easier to navigate than the MISO DB tables

We actually have plans to work on something very similar in the near future (next few months), but we don't currently have a way for external collaborators to easily check the status of their samples.

**Comment by sklages** [comment]
ok, .. starts making fun using Pinery :-)

As you suggested, using `runs` endpoint gives me the dilution IDs of all fully-processed "samples" (=loaded on sequencer). Using these LDIs I can query the data I got from the `/samples` endpoint. 
But in this json output I do find all library- and dilution-related stuff, but just the sample ID, without any data about the sample itself.

If I wanted to have e.g. the sample concentration and status (because I want to provide data for the complete path `sample -> run`), I need to re-query the database with the specific sample-ID endpoint, e.g. http://my_server.de/pinery-miso/sample/SAM13553 for each sample?

Is that correct? 

Is there a simpler way to get the **(MISO-)sample-related** stuff all at once?

**Comment by djcooke** [comment]
You can either get a single sample/library/aliquot(dilution) using the endpoint you mentioned - `http://my_server.de/pinery-miso/sample/SAM13553`

Or you can get all of the samples/libraries/aliquots at once using `http://my_server.de/pinery-miso/samples`

If you're navigating through the data by hand, it might be easier to look up one sample at a time. Programmatically, it's probably faster to get all of the samples at once and pick the ones you need out of that.

To get all of the sample information, you'll have to look at the library aliquot's parent library, and the library's parent sample.

**Comment by sklages** [comment]
ooops, my wrong :-(

I used `/runs` and then - via `LDInnn` - I looked at `/samples` output. There I just looked for the dilution and its `parents`. I did not look for the "grandparents" ;-) 
`LDI -> LIB -> SAM`, so I missed the `sample` record.

All fine, I have info about runs and its dilutions from `/runs`, I also have all infos about SAM/LIB/LDI in `/samples` endpoint data.

I am closing the issue for now. Thanks for your suggestions.
