### ISSUE TITLE
Problems with installation: 405 code on the login page

### ISSUE THREAD

**Issue by anton-khodak** [miso-lims/miso-lims#2078]
Hello,

I am following the installation instruction for MISO detailed sample mode: https://miso-lims.github.io/miso-lims/latest/adm/compose-installation-guide. I managed to start MISO, however, once I enter credentials, I am redirected to a blank page, and the logs show that POST method is not allowed:
```
nginx_1   | 172.20.243.139 - - [04/Oct/2019:13:40:16 +0000] "GET /miso/login HTTP/1.1" 200 5010 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:69.0) Gecko/20100101 Firefox/69.0" "-"
nginx_1   | 172.20.243.139 - - [04/Oct/2019:13:40:16 +0000] "GET /miso/constants.js?ts=26169940 HTTP/1.1" 500 4088 "http://miso-test.cellgeni.sanger.ac.uk/miso/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:69.0) Gecko/20100101 Firefox/69.0" "-"
nginx_1   | 172.20.243.139 - - [04/Oct/2019:13:40:30 +0000] "POST /login HTTP/1.1" 405 0 "http://miso-test.cellgeni.sanger.ac.uk/miso/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:69.0) Gecko/20100101 Firefox/69.0" "-"
nginx_1   | 172.20.243.139 - - [04/Oct/2019:13:40:30 +0000] "GET /favicon.ico HTTP/1.1" 404 1085 "http://miso-test.cellgeni.sanger.ac.uk/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:69.0) Gecko/20100101 Firefox/69.0" "-"
```
Once I come back to the main page, I have the login page again.

MISO version is  `0.2.190`
these are the images:
```
misolims/miso-lims-webapp      latest              4cc9dd6e4aac        7 days ago          178MB
misolims/miso-lims-migration   latest              31f4836fd2d2        7 days ago          116MB
```

**Comment by djcooke** [comment]
Hello, can you please provide the follow to help us troubleshoot?

* entire docker-compose file
* any error messages or stack traces that appear in /storage/miso/log/miso_debug.log

**Comment by anton-khodak** [comment]
This is the docker-compose file: https://github.com/miso-lims/miso-lims/blob/develop/.docker/demo.detailed.yml 

Here is the log: https://gist.github.com/anton-khodak/9a7262ea2429e040e46e4bf605c0d205

**Comment by djcooke** [comment]
I just tried running the detailed sample docker compose demo using the instructions in the Compose Install Guide that you linked above. It ran properly for me, though it looks like we've moved some files around and I will update the instructions to reflect that. This doesn't seem to be the issue though.

The error in your log is because the `SequencingParameters.readLength2` database column is missing. This was added in the latest official release, which is what you're running. This means Flyway probably isn't running successfully. Can you run `docker-compose -f demo.detailed.yml up` and copy the output from the flyway container here?

**Comment by djcooke** [comment]
I found and fixed the problem. Flyway migration V0793 was failing because it used a stored procedure that has since been updated to include a field that didn't yet exist at the time that that migration was added. V0793 adds some type data to make the demo installation easier to use. I updated it to not use any stored procedures.

Our release procedure tests the demo Docker Compose installations before deploying them, but unfortunately our procedure did not involve pruning the database volume, so we were effectively only testing new migrations. I will be updating our release procedure to fix that.

This fix should be included in the October 24 release. After the PR is merged, I'll update this issue with instructions for trying it out before the official release.

**Comment by djcooke** [comment]
The fix is merged. You can use the following to try it out before the official release:

```
git clone https://github.com/miso-lims/miso-lims.git
cd miso-lims
git checkout develop
git pull
docker-compose -f docker-compose.detailed.yml build
export MISO_DB_USER=tgaclims && export MISO_DB=lims && export MISO_DB_PASSWORD_FILE=./.miso_db_password
echo "changeme" > ./.miso_db_password
docker-compose -f docker-compose.detailed.yml up
```

Thanks for reporting the issue. Please reopen or create another issue if you still have trouble after this fix.
