### ISSUE TITLE
Q: Sorting Issue

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2156]
We have some 13000 library dilutions in MISO.
Going to `Preparation/Library Aliquots` and searching for a (part of a) name, e.g. `1887` shows me some 11 records. OK.
When I now want the results to be sorted by `Alias`, it takes ages (just by clicking on the column title).

Server/storage are okay, not any load from other software. Is there more sorted in the background than just these 11 records?

Just curious :-)

This is still
- mysql  Ver 14.14 Distrib 5.7.20
- Apache Tomcat/8.5.24
- MISO Version: 0.2.196

**Comment by djcooke** [comment]
A bug fix in v0.2.196 caused some slow-downs, especially related to library aliquots, so that is most likely what you are seeing. v0.2.197 includes some performance improvements that make up for it. I've just tested v0.2.197 searching 34,000 library aliquots for "1887," which quickly produced 27 records, and then sorting them by alias was also quick (roughly 1.5 seconds).

**Comment by sklages** [comment]
ok, perfect. So I simply keep waiting for  v0.2.197. thanks :+1:
