### ISSUE TITLE
Q: Possible to switch between "Plain Sample Mode" <-> "Detailed Sample Mode"?

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2317]
We are currently thinking about testing the "Detailed Sample Mode" in MISO. 

Is it possible to switch to "Detailed Sample Mode" via `miso.properties:miso.detailed.sample.enabled:true` and switch back after some time to "Plain Sample Mode" via the same property?

**Comment by djcooke** [comment]
Switching between plain and detailed sample modes is not supported. The data is not compatible, and would cause a lot of errors. You would have to start with a new database.

**Comment by sklages** [comment]
... and there is probably no way to migrate the data from plain to detailed data model?

**Comment by djcooke** [comment]
There's no simple way. You could do it by transforming your plain sample data to detailed sample data outside of MISO. You'd have to:

1. Create all of the dropdown values that are specific to detailed sample mode (sample classes, tissue types, tissue origins, library design codes, etc.). You could probably switch to detailed sample mode and do this within MISO... I think you would only get errors when trying to work with samples, libraries, aliquots, pools, containers, runs, and maybe some other things. Because switching isn't supported, we haven't done any testing for it. The below steps, you would not be able to do from within MISO, so you'd have to use SQL or write a separate program.
1. Update all libraries and library aliquots to include values for some detailed fields
1. Assume all of your samples are aliquots. Update them to include values for any required detailed sample aliquot fields
1. Create stock samples for all of the aliquots, and update the aliquots to be parented to the stocks
1. Create tissue samples for all of the stocks, and update the stocks to be parented to these tissues
1. Create identity samples for all of the tissues, and update the tissues to be parented to these identities

A lot of the fields that are required for these parent samples could just be copied from the child sample. Others, there may be sensible defaults for, or you could create "Unknown" values. Others would be more difficult. Generating aliases may be tricky depending on your naming scheme and how you want to handle them.

An easy way to try out detailed sample mode is to use the demo Docker container, as detailed in the readme: https://github.com/miso-lims/miso-lims/blob/develop/readme.md

**Comment by sklages** [comment]
hmm, okay, thanks. Seems that migration is not an easy (possible) option. 

We have ~17K samples in MISO, so starting from the very beginning isn't an option neither ... 

I thought that plain/detailed modes are UI options working on the same database scheme (with some "default" values for those values not used in plain sample mode).
