### ISSUE TITLE
Problems while Updating MISO-LIMS version 1.6.0 to 1.7.0

### ISSUE THREAD

**Issue by wgunia** [miso-lims/miso-lims#2374]
Dear Miso-Team,

I'm asking for your support as I'm strugglin

For handling large amount of data in the laboratory the MIS-LIMS system version 1.6.0
(Earlham Institute, Ontario Institute for Cancer Research) was installed.
This version is running perfectly.
Then I tried to update the next version 1.7.0 of miso-lims.

Building the software using Apache Maven 3.0.5 in a first step has been accomplished successfully.

For the second relevant step flyway5.2.4 has been applied to migrate the database.
This process terminated with errors:
- Error Code : 1050
  Message    : Table 'Sop' already exists
(Should I delete the Sop-table?)
Details can be seen in the logfile.
[flyway5.2.4_migrate.log](https://github.com/miso-lims/miso-lims/files/5383475/flyway5.2.4_migrate.log)

Since the migration has been interrupted, the database is nearly empty.
Some project data can be seen using the web interface.
But sample-ID data lost completely.
Thus is was necessary to restore miso-lims version 1.6.0.
What went wrong?

Thank you very much for any help.

Cheers
Wilfried

**Comment by djcooke** [comment]
Hello Wilfried,

The Sop table shouldn't exist before version 1.7.0. If you created it yourself, you will have to delete it before you can run the upgrade/migration.

If you did not create the Sop table yourself, it's possible that version 1.6.0 was not installed correctly and some unreleased migrations were run. This would happen if you had built MISO from the develop branch instead of checking out the tagged release. Please run the following SQL and post the results, then we can determine what happened and how to resolve:

```
SELECT * FROM flyway_schema_history;
```

**Comment by wgunia** [comment]
Hello Dillan,
 Thanks for your response.
The contents of flyway_schema_history-table is in the attached logfile.
[flyway_schema_history.txt](https://github.com/miso-lims/miso-lims/files/5390230/flyway_schema_history.txt)

Thank you very much for any help.

Cheers
Wilfried

**Comment by djcooke** [comment]
Your schema history looks as it should, so I don't know how the Sop table already exists. It should be created in the V1090 migration, which was added in MISO v1.7.0 and has not been run yet.

It should be fine to drop the table and then retry the migration.

**Comment by wgunia** [comment]
Thank you for this hint.

The migration has been accomplished successfully.
