### ISSUE TITLE
RunScanner/MISO: NextSeq 2000 Support?

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2433]
When trying to setup our new `NextSeq 2000` I get an error with `Run Scanner` (**v1.12.1 from 05/2020**):

```
ERROR   2021-01-16 12:49:00,165 [ForkJoinPool-1-worker-3] 
ca.on.oicr.gsi.runscanner.scanner.Scheduler  - Failed to process run: 
/path/to//210113_ID_1_AAACK55HV
```
Probably due to lack of support of `NextSeq 2000`? 
If so, are you planning to support `NextSeq 2000` in near future?

**Comment by sklages** [comment]
ok, current version is working neither:
```
✔  runscanner-illumina [v1.12.3|✚ 1]
➤  ./runscanner-illumina $RUN_DIR | grep -v metrics
Exception from Illumina interop parser for run in /path/to/NS2000-Run: 
  No format found to parse ErrorMetricsOut.bin with version: 5 of 2
/path/to/runscanner-illumina/interop/./interop/io/metric_stream.h::read_metrics (111)
```

**Comment by avarsava** [comment]
Hello sklages,

I'm sorry to hear about your trouble using Run Scanner using NextSeq 2000. 
In the Run Scanner documentation, there is a list of sequencers currently supported by Run Scanner:
https://miso-lims.readthedocs.io/projects/runscanner/en/latest/appendices/#appendix-c-sequencers-supported-by-run-scanner

However, so long as the output of the NextSeq 2000 is the same as a supported sequencer, then the NextSeq 2000 should work with Run Scanner, with the disclaimer that we cannot guarantee its accuracy as we have not tested it ourselves. It looks like your issue is in the Illumina interop parser, which should be able to parse every Illumina sequencer's output. Could you please confirm that you updated and rebuilt illumina-interop when testing the latest version of Run Scanner?
https://miso-lims.readthedocs.io/projects/runscanner/en/latest/illuminasetup/

Beyond the interop parser, however, we currently do not have any plans to support the NextSeq 2000. We welcome PRs for support of new sequencers. Alternatively, please let me know if you'd be interested in sponsoring development of this feature for Run Scanner.

Regards,

Alexis Varsava

**Comment by sklages** [comment]
For some reason, on a fresh `clone`, there is always interop parser **`v1.1.8`** checked out. I didn't notice that before.
After `git submodule init && git submodule update` I needed to explicitly  checkout current version, e.g.:
```
IOP_VERSION=v1.1.19
cd runscanner-illumina/interop
git checkout $IOP_VERSION
cd ..

./build-illumina-interop

[...]
```
The command line `runscanner-illumina` is now working for NextSeq2000 data, and so does the web interface.
