### ISSUE TITLE
Q: Some SQL/DB Warnings

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2458]
Just curious how to fix this. I get a few warnings which I'd like to get rid of :-)

```
Current version of schema `miso_seqcore`: 1220
WARNING: outOfOrder mode is active. Migration of schema `miso_seqcore` may not be reproducible.
Migrating schema `miso_seqcore` to version 1230 - auto main
[...]
WARNING: DB: Incorrect date value: '2018-01-04 16:11:37' for column 'qcDate' at row 5 (SQL State: 22007 - Error Code: 1292)
WARNING: DB: Incorrect date value: '2018-01-04 16:11:38' for column 'qcDate' at row 5 (SQL State: 22007 - Error Code: 1292)
WARNING: DB: Incorrect date value: '2018-01-04 16:11:39' for column 'qcDate' at row 5 (SQL State: 22007 - Error Code: 1292)
[...]
WARNING: DB: Incorrect date value: '2020-07-10 08:38:42' for column 'dataReviewDate' at row 7 (SQL State: 22007 - Error Code: 1292)
WARNING: DB: Incorrect date value: '2020-07-14 15:47:49' for column 'dataReviewDate' at row 5 (SQL State: 22007 - Error Code: 1292)
WARNING: DB: Incorrect date value: '2020-07-15 16:50:37' for column 'dataReviewDate' at row 7 (SQL State: 22007 - Error Code: 1292)
```
The `outOfOrder` warning is there for quite a while. Not sure how to fix this ..

Since current (1.23.0) update I get a bunch of these "Incorrect date value" warnings. Is there a way to fix this?
Well, okay, it is just a warning ... 

Here I run `MySQL 5.7`  with `Flyway Community Edition 5.2.4 by Boxfuse`.

**Comment by djcooke** [comment]
Hello,

These messages can be ignored. There is no problem and nothing to fix.

* The "outOfOrder mode" message will show up during every migration. This is a normal part of how the migration is run.
* The date warnings will only show up once - during migration to version 1230. This is because some new date fields are initialized from existing timestamps (date+time). The warning is because while the date is being set correctly, the time part is being lost. This was our intention, so not a problem

**Comment by sklages** [comment]
okay, thanks for the explanation. :+1:
