### ISSUE TITLE
miso lims demo.plain showing 404 not found error

### ISSUE THREAD

**Issue by code4plot** [miso-lims/miso-lims#2568]
I installed miso-lims with docker compose and tried out the demo following the given instructions.
When I navigate to localhost/miso, I get a 404 not found error.

![image](https://user-images.githubusercontent.com/57120354/133727708-16564503-0a1d-46fe-a7ef-71b1f75338ac.png)

**Comment by avarsava** [comment]
Hi code4plot! 
I'm sorry to hear you're having issues using the docker-compose demo of miso-lims.

As per the miso-lims README, after the docker image comes up, you should navigate directly to `localhost` and log in with the credentials `admin/admin`: https://github.com/miso-lims/miso-lims#readme
I tried navigating to `localhost/miso` with the plain sample demo and was able to replicate this 404.
Can you please confirm that navigating directly to `localhost` clears the issue? Otherwise, please let me know what happens and I will investigate further.

Regards,
Alexis

**Comment by code4plot** [comment]
Hi avarsava, thanks for pointing out the README - when I navigate to `localhost`, I can login and load up the demo dashboard.

I was following the instructions provided here: https://miso-lims.readthedocs.io/projects/docs/en/latest/admin/compose-installation-guide/#quick-start
which instructs first-time users to navigate to `localhost/miso`.  
![image](https://user-images.githubusercontent.com/57120354/133914645-dd111278-ad30-48f8-845b-3383e1e069e6.png)

Thanks again!

**Comment by avarsava** [comment]
You're welcome - I'm glad this issue's been cleared!
And thank you for pointing out the issue with the readthedocs site - I'll make sure this page is updated.
