### ISSUE TITLE
Error when using Unique Dual Indices

### ISSUE THREAD

**Issue by bmatlas** [miso-lims/miso-lims#2599]
We have created an ‚Index Family‘ with Unique Dual Indices (UDI) in ‚Position‘ 2. When we ‚Propagating aliquots to libraries‘ and use this index family and select UDI from the drop-down list, the library is saved without error, but no index family and index is applied. When try to edit the library and select this index family an error message is displayed:
  
‚An unexpected JavaSript error has occurred.
Please file a ticket letting us know what you were trying to do when this happened.‘

Do you have any idea what is going wrong?

**Comment by djcooke** [comment]
Hello,

Thanks for reporting this. We'll need a bit more information in order to find the problem.

1. What version of MISO are you using? The version is displayed at the very bottom of the page.
2. Which web browser are you using?
3. Which operating system are you using?
4. Which page does the JavaScript error occur on? Is it the single Edit Library page, or the bulk Edit Libraries page?
5. At what point does the error occur? Is it when the page loads, when you click an option in the Index Family dropdown, or at some other point?
6. Can you provide the stack trace for this error? To find this, open the developer console (F12 on most browsers) and trigger the error. The stack trace will list files and line numbers, and would be very helpful.
7. If you have access to the database, you can check whether the indices saved properly, as this may just be a display problem. Use the query below to check, replacing 12345 with the library ID. If the results are `NULL` then the indices did not save on the library.

```
SELECT index1Id, index2Id FROM Library WHERE libraryId = 12345;
```

**Comment by bmatlas** [comment]
Hi, 
Thank you for responding promptly.
PLease find the answers below.

>  1. What version of MISO are you using? The version is displayed at the very bottom of the page.

Version: 1.39.1

>  2. Which web browser are you using?

Tested:
Firefox 70.0b13 (64-Bit)
Firefox 95.0.2 (64-Bit)
Microsoft Edge Version 96.0.1054.62 (64-Bit)

>  3. Which operating system are you using?

Tested
Windows Server 2012 Version 6.3 (Build 9600)
Windows 10 Version 21H1 (Build 19043.1415)

>  4. Which page does the JavaScript error occur on? Is it the single Edit Library page, or the bulk Edit Libraries page?
Single Edit Library page
In bulk Edit Libraries are the libraries saved without error, but still no index family and index is applied.

**Comment by bmatlas** [comment]
Sorry, I sent too fast, here are the rest of the answers.

>  5. At what point does the error occur? Is it when the page loads, when you click an option in the Index Family dropdown, or some other point?

As soon as select the Index Family in dropdown.

>  6. Can you provide the stack trace for this error? To find this, open
>     the developer console (F12 on most browsers) and trigger the error.
>     The stack trace will list files and line numbers, and would be very
>     helpful.

`Error: unique element not found
    findUniqueOrThrow http://lims.XXX/scripts/header_script.js?version=1.39.1:21191
    onChange http://lims.XXX/scripts/header_script.js?version=1.39.1:11455
    triggerUpdate http://lims.XXX/scripts/header_script.js?version=1.39.1:8682
    updateField http://lims.XXX/scripts/header_script.js?version=1.39.1:8783
    onChange http://lims.XXX/scripts/header_script.js?version=1.39.1:11264
    makeDropdownInput http://lims.XXX/scripts/header_script.js?version=1.39.1:9193
    jQuery 2
header_script.js:29:11
Uncaught Error: unique element not found
    findUniqueOrThrow http://lims.XXX/scripts/header_script.js?version=1.39.1:21191
    onChange http://lims.XXX/scripts/header_script.js?version=1.39.1:11455
    triggerUpdate http://lims.XXX/scripts/header_script.js?version=1.39.1:8682
    updateField http://lims.XXX/scripts/header_script.js?version=1.39.1:8783
    onChange http://lims.XXX/scripts/header_script.js?version=1.39.1:11264
    makeDropdownInput http://lims.XXX/scripts/header_script.js?version=1.39.1:9193
    jQuery 2
header_script.js:21191:13`



>  7. If you have access to the database, you can check whether the indices saved properly, as this may just be a display problem. Use the query below to check, replacing 12345 with the library ID. If the results are |NULL| then the indices did not save on the library. 
|SELECT index1Id, index2Id FROM Library WHERE libraryId = 12345; |

+----------+----------+
| index1Id | index2Id |
+----------+----------+
|     NULL |     NULL |
+----------+----------+
1 row in set (0.00 sec)

Thanks

**Comment by djcooke** [comment]
Thanks for providing all of that information. I think I found the issue. I was able to reproduce this error by creating an index family with no indices.

When creating libraries, the index family you select is not a saved field - it is only used to populate the Index 1 and Index 2 columns. When you choose indices in these columns, this is what gets saved. Normally when you select an Index Family, the Index 1 column becomes required, but if there are no indices in the index family, then it is ignored.

On the Edit Library page, the error you posted above is thrown when you select an index family that has no indices.

You can fix the problem by adding indices to your index family. Please let me know if your index family does already have indices, and I will investigate further possible causes.

I will modify both pages to display a more helpful message when selecting an index family that has no indices so the problem is clearer in the future.

**Comment by bmatlas** [comment]
Thank you for the helpful hints. 

I found out that the position of the index in the Index Family was the problem. The Index Family was created with indices at position 2. Changing the indices within the Index Family to position 1 solved the problem.

**Comment by djcooke** [comment]
Improved error messages: https://github.com/miso-lims/miso-lims/pull/2600
