### ISSUE TITLE
An unexpected JavaSript error has occurred - Accessing Library Aliquots ID's

### ISSUE THREAD

**Issue by jayramr** [miso-lims/miso-lims#2663]
Hello,

I'm getting below warning whenever i choose  to open project/library/sample. As there is a dialog box coming every time and i need to press OK two times, then only it permits me to go to that page

---
DataTables warning (table id = 'project_libraryAliquots'): Requested unknown parameter 'effectiveTissueOriginAlias' from the data source for row 0
---

In addition I'm getting another Javascript error while opening any "Library Aliquots ID", but at the same time no error with opening library ID

---
An unexpected JavaSript error has occurred.
Please file a ticket letting us know what you were trying to do when this happened.
---

Please advise why I'm getting this warning/error. Also let me know how to enable more debugging on miso_debug.log file, so i can see some pointers what could be the reason for these errors. 

Please advise

**Comment by djcooke** [comment]
Hello,

I'm guessing you may have switched your MISO config between running in plain sample mode and detailed sample mode, which will cause many problems and is not supported. If this is the case, please either switch back to the original mode you were using, or delete all samples that were created in the original mode.

If that is not the case, please check the JavaScript console in your browser for extra debugging information and post it here. Since this is a front-end/JavaScript error, it will not appear in the MISO debug log.

**Comment by jayramr** [comment]
Hi,

This is running as a plain mode build. Also attached the docker yaml file which we used for this prod build

[](url)

<img width="1717" alt="image" src="https://user-images.githubusercontent.com/97015642/169038904-6d996451-443a-49ec-8c8f-36c663e57787.png">
[docker_prod.txt](https://github.com/miso-lims/miso-lims/files/8716199/docker_prod.txt)
