### ISSUE TITLE
Q: MISO Update: SSL (HTTPS) is now required for MISO logins to function correctly over a network.

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2678]
Well, we are running `1.43.2`, in `1.43.3` "Upgrade Notes" state:

```
SSL (HTTPS) is now required for MISO logins to function correctly over a network. 
HTTP can only be used for localhost connections (development/testing)
```

Our production server is accessible inside our LAN only. Like `miso.our.domain.de`.

We are running a baremetal installation:
* git clone, checkout version
* build MISO using `mvn`
* migrate database 
* copy some configs
* start & use MISO

I'd appreciate some docs on SSL configuration (outside a docker installation) using a self-signed certificate.

Certificate creation:

```
# create cert
openssl req \
  -x509 \
  -keyout miso.key.pem \
  -out miso.cert.pem \
  -days 730 \
  -nodes \
  -subj "/C=DE/ST=City/L=Here/O=XXX/OU=SeqCore/CN=miso.our.domain.de"
```

* how do I modify `server.xml` to accept this certificate?
* is this the only file I need to modify?
* where do I get the chain file from?

I was able to compile `1.44.0` and successfully start MISO without SSL (http) and without any issues.
So I am a bit confused as I thought this would not be possible with this version ... 

I did rollback to `1.43.2` for current use ..

Can you help on that?

**Comment by djcooke** [comment]
The change that caused this is that the session cookie is now marked "secure," which means it will only be transmitted over HTTPS. This cookie is used to track the user login. As you observed, you were able to successfully start MISO. If you try to log in, you will just keep getting kicked back to the login screen, however. This is because your browser won't send the cookie over HTTP, and so the server will not see that the user is already logged in.

Our preference is to leave Tomcat in its default configuration and use NGINX as a proxy in front of Tomcat. We configure SSL in NGINX, and also set up an automatic redirect from HTTP to HTTPS. Here is an example config to do this. The config assumes a default Tomcat config (serving on port 8080), and handles standard HTTP and HTTPS ports. If you didn't put a password on your key, you can omit the `ssl_password_file` line: https://github.com/miso-lims/miso-lims/blob/v1.45.0/.docker/nginx/ssl.conf

If you would prefer to use Tomcat alone, you can see the guide here: https://tomcat.apache.org/tomcat-9.0-doc/ssl-howto.html

Let me know if you have any other questions.

**Comment by sklages** [comment]
OK, configured tomcat to use a self-signed certificate .. works fine :-)
