### ISSUE TITLE
Q: user / group management

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2836]
I remember loosely that in very early versions of MISO (TGAC/Earlham) we were able to create users and groups with restricted access to MISO.

E.g. in a given project we have samples which belong to group "Cancer01". This group has one user "Smith". In early versions it was possible (AFAIR), that this user, once logged in, could see the data (samples, libs, whatever) assigned to him or his group, no other data.

In "plain sample mode" this seems not to be possible anymore. A freshly created user can (at least) see "everything".

Is this something that is possible in "detailed sample mode"?

If not, what is the purpose of a user not being "internal", as this user cannot log in into MISO?

And maybe a question to this point: 
- how do you implement that (external/internal) users/customers are able to see **only their** orders/sample/libraries and the corresponding QCs? Did you set up another server where you present some mangled data from Pinery webservice? How do you provide customers/users with relevant order/sample/QC information? Is that possible with MISO?

**Comment by djcooke** [comment]
Early versions of MISO did have some user and group-level permissions on projects, samples, and some other items, but they were not working correctly and we removed them rather than fixing and maintaining them. We have had interest in more fine-grained permissions, but no work is planned at this time. As is, we intend MISO to be used by internal users only, and all users have access to all projects, samples, etc.

**Comment by djcooke** [comment]
> If not, what is the purpose of a user not being "internal", as this user cannot log in into MISO?

There is no purpose, and we should really remove this field

**Comment by sklages** [comment]
ok, thanks for clarification.
